### ISSUE TITLE
Where is model definition itself?

### ISSUE THREAD

**Issue by mrgloom** [desimone/pytorch-cat-vs-dogs#1]
Where is model definition itself?
I can't see it in this file:
https://github.com/desimone/pytorch-cat-vs-dogs/blob/master/main.py

**Comment by desimone** [comment]
It's imported from [pytoch vision](https://github.com/pytorch/vision).

Specifically, I'm fine-tuning the final layer `net.fc`, the classifier.

https://github.com/pytorch/vision/blob/master/torchvision/models/resnet.py#L150

```python
    def forward(self, x):
        x = self.conv1(x)
        x = self.bn1(x)
        x = self.relu(x)
        x = self.maxpool(x)

        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)
        x = self.layer4(x)

        x = self.avgpool(x)
        x = x.view(x.size(0), -1)
        x = self.fc(x)

        return x
```
