### ISSUE TITLE
error running main.py

### ISSUE THREAD

**Issue by brisker** [desimone/pytorch-cat-vs-dogs#3]
jcc@jcc:~/pytorch/tutorials/pytorch-cat-vs-dogs$ python main.py --data './catdog'
usage: main.py [-h] [--arch ARCH] [--workers N] [--epochs N] [--start-epoch N]
               [-b N] [--lr LR] [--momentum M] [--weight-decay W]
               [--print-freq N] [--resume PATH] [--evaluate] [--test]
               [--pretrained]
               DIR
main.py: error: unrecognized arguments: --data
The parser augument already has default values, why this happens? I am using Python2.7, any help?

**Comment by desimone** [comment]
data is an unnamed command line argument. Just pass it in directly. 

`python main.py /tmp/data/dir/whatever`
